### ISSUE TITLE
k8s-freeflow

### ISSUE THREAD

**Issue by gangliao** [Microsoft/Freeflow#2]
Follow my prev issue #1, I found it's too hard to contribute k8s/etcd code in this official repo [Still have some compile/link error in your repo]. So I create a new repo to hack it and verify some idea.  Since someone may be interested in it, I post some progress at here.

# k8s-freeflow

## TO-DO List

- [x] IP Hunter: write changed nodes and map(vip, pip) into ETCD periodically [CODE](https://github.com/gangliao/k8s-freeflow/blob/master/ip_hunter/ip2etcd.go)
- [x] IP Hunter's Docker Image [CODE](https://github.com/gangliao/k8s-freeflow/blob/master/ip_hunter/run.sh)

- [x] **Have yet Test** ffrouter update HOST_LIST and vip_map via RESTful API of ETCD's Watch mode periodically**. [CODE](https://github.com/gangliao/k8s-freeflow/blob/master/freeflow/ffrouter/ffrouter.cpp#L6-L168)

- [x] [ffouter docker image](https://github.com/gangliao/k8s-freeflow#build-freeflow-router-image)

- [x] [client docker image](https://github.com/gangliao/k8s-freeflow#build-freeflow-client-image)

- [x] GoogleTest **PASS**: ETCD V3 API's watch mode for ffrouter [CODE](https://github.com/gangliao/k8s-freeflow/blob/master/freeflow/ffrouter/etcd_test.cpp#L245-L297)

    The Watch API provides an event-based interface for asynchronously monitoring changes to keys. An etcd3 watch waits for changes to keys by continuously watching from a given revision, either current or historical, and streams key updates back to the client. https://coreos.com/etcd/docs/latest/learning/api.html

- [x] GoogleTest **PASS**: ETCD V3 API's range mode for ffrouter
- [x] GoogleTest **PASS**: ETCD V2 API's put mode for ffrouter

- [x] new ffrouter depends on curl, base64 and jsoncpp. [CODE](https://github.com/gangliao/k8s-freeflow/tree/master/freeflow/ffrouter/cmake)
- [x] the process of compilation passed. [CODE](https://github.com/gangliao/k8s-freeflow/blob/master/freeflow/ffrouter/CMakeLists.txt)

- [ ] **testing new ffouter with IP hunter and fix bug.**
- [ ] IP Hunter -> Kubernetes POD: ip_hunter_pod.yaml
- [ ] ffrouter -> Kubernetes Daemonset: ffrouter_daemonset.yaml
- [ ] Benchmark: baseline Kubeflow
